services:
  mongodb:
    image: mongo:7
    container_name: rhm-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - rhm-mongo-data:/data/db

volumes:
  rhm-mongo-data:
